### ISSUE TITLE
Compile tl-wr1043ndv2 firmware error

### ISSUE THREAD

**Issue by dnybz** [freebsd/freebsd-wifi-build#117]
Hi, all
    I was in the translation tl-wr1043ndv2 firmware error
Error message:
*** Target Done.
*** Target              : mfsroot
*** Deleting old file system..
*** Creating new filesystem...
*** Populating filesystem...
*** Including modules..
*** Target Done.
*** Target              : addpkgs
*** Adding package dropbear to rootfs
tar: Error opening archive: Failed to open '/data/freebsd/head/src/../pkgdir/mips_ap/dropbear.tar.gz'
$

**Comment by erikarn** [comment]
Sounds like I'm mssing a fetch step. :( ok.



-a

**Comment by Cka3o4Huk** [comment]
Thanks, Adrian!  I suppose issue is resolved now.
