### ISSUE TITLE
Hi, how to add Rockchip RK3188 support. 

### ISSUE THREAD

**Issue by dnybz** [freebsd/freebsd-wifi-build#123]
Hi, how to add Rockchip RK3188 support. Thx! :)
https://wiki.freebsd.org/FreeBSD/arm/Radxa%20Rock

**Comment by Cka3o4Huk** [comment]
Hi,

What is your board? 
BTW, look at https://github.com/freebsd/crochet/tree/master/board/RadxaRock

**Comment by dnybz** [comment]
Hi

   My board is Radxa Rock Lite, is sdcard boot. Thx! :)
https://github.com/freebsd/crochet/blob/master/board/RadxaRockLite

**Comment by Cka3o4Huk** [comment]
@dnybz , it's just symbolic link to RadxaRock: https://github.com/freebsd/crochet/tree/master/board/RadxaRock

**Comment by dnybz** [comment]
Thx! :)
