### ISSUE TITLE
Hi, how to add MT7628 support.

### ISSUE THREAD

**Issue by dnybz** [freebsd/freebsd-wifi-build#125]
Hi 

 how to add MT7628 support.  Thx !    :)

**Comment by Cka3o4Huk** [comment]
I didn't test it, but plan to do it:
https://forums.freebsd.org/threads/61630/
X_DTS_FILE=MT7628.dts KERNCONF=MT7628_FDT ../../build/build/bin/build ralink

**Comment by dnybz** [comment]
Hi , Thx :) .  I use `X_DTS_FILE=MT7628.dts KERNCONF=MT7628_FDT ../../build/build/bin/build ralink` 
 compiler, an error when generating image files

Can't locate mfs section within kernel

*** Target              : mfsroot
*** Deleting old file system..
chflags: /data/freebsd/head/src/../mfsroot/ralink: No such file or directory
*** Creating new filesystem...
*** Populating filesystem...
install: /data/freebsd/head/src/../root/mipsel_ap/usr/local/bin/wlanwds: No such file or directory
*** Target Done.
*** Target              : fsimage
*** Running makefs to build compressed image ..
*** from /data/freebsd/head/src/../mfsroot/ralink ..
Calculated size of `/data/freebsd/head/src/../img//mfsroot-ralink.img': 18882560 bytes, 1267 inodes
Extent size set to 4096
/data/freebsd/head/src/../img//mfsroot-ralink.img: 18.0MB (36880 sectors) block size 4096, fragment size 512
        using 2 cylinder groups of 12.95MB, 3315 blks, 928 inodes.
super-block backups (for fsck -b #) at:
    32, 26552,
Populating `/data/freebsd/head/src/../img//mfsroot-ralink.img'
Image `/data/freebsd/head/src/../img//mfsroot-ralink.img' complete
*** Running mkuzip to create a compressed filesystem ..
*** Target Done.
*** Target              : netboot
Can't locate mfs section within kernel

**Comment by dnybz** [comment]
Hi 

       build error in this line， i hope to get your help!  Thx!  :)
https://github.com/freebsd/freebsd-wifi-build/blob/master/build/bin/build_netboot#L31

I am run command 
 # /data/freebsd/head/obj/mipsel_ap/data/freebsd/head/src/mips.mipsel/tmp/usr/bin/objdump -h /data/freebsd/head/root/mipsel_ap/boot/kernel.MT7628_FDT/kernel.netboot

/data/freebsd/head/root/mipsel_ap/boot/kernel.MT7628_FDT/kernel.netboot:     file format elf32-tradlittlemips

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         0035c580  80001100  80001100  00001100  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .MIPS.stubs   00000010  8035d680  8035d680  0035d680  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  2 .rodata       0006eadc  8035d690  8035d690  0035d690  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 set_sysctl_set 000012d0  803cc16c  803cc16c  003cc16c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 set_sysuninit_set 000004f0  803cd43c  803cd43c  003cd43c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 set_sysinit_set 000009ec  803cd92c  803cd92c  003cd92c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 set_cam_xpt_xport_set 00000028  803ce318  803ce318  003ce318  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 set_modmetadata_set 00000524  803ce340  803ce340  003ce340  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  8 set_cam_xpt_proto_set 00000010  803ce864  803ce864  003ce864  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 set_kdb_dbbe_set 00000008  803ce874  803ce874  003ce874  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 10 set_ofw_set   00000004  803ce87c  803ce87c  003ce87c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 11 set_uart_fdt_class_and_device_set 00000004  803ce880  803ce880  003ce880  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 12 set_cons_set  00000008  803ce884  803ce884  003ce884  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 13 usb_host_id   00000020  803ce8a0  803ce8a0  003ce8a0  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 14 .interp       0000000d  803ce8c0  803ce8c0  003ce8c0  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 15 .hash         0000b3fc  803ce8d0  803ce8d0  003ce8d0  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 16 .dynsym       0001cfa0  803d9ccc  803d9ccc  003d9ccc  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 17 .dynstr       0001d192  803f6c6c  803f6c6c  003f6c6c  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 18 .reginfo      00000018  80413e00  80413e00  00413e00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA, LINK_ONCE_DISCARD
 19 .data         0003dec0  80416000  80416000  00416000  2**13
                  CONTENTS, ALLOC, LOAD, DATA
 20 .rld_map      00000004  80453ec0  80453ec0  00453ec0  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 21 oldmfs        00600000  80453ec4  80453ec4  00453ec4  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 22 set_pcpu      00000d04  80a53f00  80a53f00  00a53f00  2**6
                  CONTENTS, ALLOC, LOAD, DATA
 23 .got          00001b5c  80a54c10  80a54c10  00a54c10  2**4
                  CONTENTS, ALLOC, LOAD, DATA
 24 .dynamic      000000c8  80a5676c  80a5676c  00a5676c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 25 .bss          0008dc20  80a56840  80a56840  00a56834  2**6
                  ALLOC
 26 .comment      00010732  00000000  00000000  00a56834  2**0
                  CONTENTS, READONLY
 27 .pdr          00050600  00000000  00000000  00a66f68  2**2
                  CONTENTS, READONLY
 28 .gnu_debuglink 00000014  00000000  00000000  00ab7568  2**0
                  CONTENTS, READONLY

**Comment by Cka3o4Huk** [comment]
Hi,
Right now buildkernel of HEAD is broken due to zstd for MIPS32LE and BE. As soon as buildkernel will be fine, I'll back to netboot. sorry for delay.

**Comment by dnybz** [comment]
Hi
Thx!  :)

**Comment by Cka3o4Huk** [comment]
Try this fix: https://github.com/freebsd/freebsd-wifi-build/pull/126
In advance, please add "options     MD_ROOT_SIZE=8000" in your local copy 'sys/mips/conf/MT7628_FDT' to create MD section

**Comment by dnybz** [comment]
Hi 
 I am add "options MD_ROOT_SIZE=8000" in /data/freebsd/head/src/sys/mips/conf/MT7628_FDT
`# Support md(4) and md-based rootfs
device          md
options         MD_ROOT
options         MD_ROOT_SIZE=8000`

Try this fix: [#126](https://github.com/freebsd/freebsd-wifi-build/pull/126/commits/8cbc9aede21bd1fe0b7f147153239c4773dc8200)

run command, 
"X_DTS_FILE=MT7628.dts KERNCONF=MT7628_FDT ../../build/build/bin/build ralink"

compile error 

*** Target Done.
*** Target              : mfsroot
*** Deleting old file system..
*** Creating new filesystem...
*** Populating filesystem...
install: /data/freebsd/head/src/../root/mipsel_ap/usr/local/bin/wlanwds: No such file or directory
*** Target Done.
*** Target              : fsimage
*** Running makefs to build compressed image ..
*** from /data/freebsd/head/src/../mfsroot/ralink ..
Calculated size of `/data/freebsd/head/src/../img//mfsroot-ralink.img': 18882560 bytes, 1267 inodes
Extent size set to 4096
/data/freebsd/head/src/../img//mfsroot-ralink.img: 18.0MB (36880 sectors) block size 4096, fragment size 512
        using 2 cylinder groups of 12.95MB, 3315 blks, 928 inodes.
super-block backups (for fsck -b #) at:
    32, 26552,
Populating `/data/freebsd/head/src/../img//mfsroot-ralink.img'
Image `/data/freebsd/head/src/../img//mfsroot-ralink.img' complete
*** Running mkuzip to create a compressed filesystem ..
*** Target Done.
*** Target              : netboot
Can't locate mfs section within kernel


Thx! :)

**Comment by Cka3o4Huk** [comment]
#126 is updated, please try again... 
I guess it's not last change, build_ralink also requires changes due to OBJ directory layout change.

**Comment by dnybz** [comment]
Hi 
    Thx! @Cka3o4Huk :)   I compiled successfully.

*** Running mkuzip to create a compressed filesystem ..
*** Target Done.
*** Target              : netboot
*** copying the mfsroot into the kernel image
*** generate md5 for /data/freebsd/head/src/../root/mipsel_ap/boot/kernel.MT7628_FDT/kernel.netboot
*** Complete.
*** Target Done.
*** Target              : ralink
/data/freebsd/build/build/bin/build_ralink: /data/freebsd/head/src/../obj/mipsel_ap/mips.mipsel//data/freebsd/head/src/tmp/usr/bin/objcopy: not found

# ls -ll /data/freebsd/head/obj/mipsel_ap/data/freebsd/head/src/mips.mipsel/tmp/usr/bin/objcopy
-rwxr-xr-x  2 dnybz  dnybz  210720 Jan  8 17:39 /data/freebsd/head/obj/mipsel_ap/data/freebsd/head/src/mips.mipsel/tmp/usr/bin/objcopy

modify the build script build_ralink
 /data/freebsd/build/build/bin/build_ralink

#T_OBJCOPY_DIR="${CUR_DIR}/../obj/${X_BUILD_BASE_CFG}/${TARGET}.${TARGET_ARCH}"
#T_OBJCOPY="${T_OBJCOPY_DIR}/${CUR_DIR}/tmp/usr/bin/objcopy"
T_OBJCOPY_DIR="${CUR_DIR}/../obj/${X_BUILD_BASE_CFG}"
T_OBJCOPY="${T_OBJCOPY_DIR}/${CUR_DIR}/${TARGET}.${TARGET_ARCH}/tmp/usr/bin/objcopy"


compiled again...

*** Target Done.
*** Target              : mfsroot
*** Deleting old file system..
*** Creating new filesystem...
*** Populating filesystem...
install: /data/freebsd/head/src/../root/mipsel_ap/usr/local/bin/wlanwds: No such file or directory
*** Target Done.
*** Target              : fsimage
*** Running makefs to build compressed image ..
*** from /data/freebsd/head/src/../mfsroot/ralink ..
Calculated size of `/data/freebsd/head/src/../img//mfsroot-ralink.img': 18882560 bytes, 1267 inodes
Extent size set to 4096
/data/freebsd/head/src/../img//mfsroot-ralink.img: 18.0MB (36880 sectors) block size 4096, fragment size 512
        using 2 cylinder groups of 12.95MB, 3315 blks, 928 inodes.
super-block backups (for fsck -b #) at:
    32, 26552,
Populating `/data/freebsd/head/src/../img//mfsroot-ralink.img'
Image `/data/freebsd/head/src/../img//mfsroot-ralink.img' complete
*** Running mkuzip to create a compressed filesystem ..
*** Target Done.
*** Target              : netboot
*** copying the mfsroot into the kernel image
*** generate md5 for /data/freebsd/head/src/../root/mipsel_ap/boot/kernel.MT7628_FDT/kernel.netboot
*** Complete.
*** Target Done.
*** Target              : ralink                                                                                                                                               Output size: 7370422 (7 MiB)                                  Image Name:   FreeBSD                                                                                                                                                                                                                        Created:      Sun Jan 14 00:21:00 2018                                                                                                                                                                                                       Image Type:   MIPS Linux Kernel Image (lzma compressed)                                                                                                                                                                                      Data Size:    7370422 Bytes = 7197.68 kB = 7.03 MB
Load Address: 80001100
Entry Point:  80001100
7+1 records in
8+0 records out
8388608 bytes transferred in 0.003871 secs (2167097230 bytes/sec)
*** Target Done.
*** Build Completed.
