### ISSUE TITLE
Hi , cfg_save error

### ISSUE THREAD

**Issue by dnybz** [freebsd/freebsd-wifi-build#128]
Hi

    I run the cfg_save command to save, but the prompt libarchive.so.6 not found.  Thx!   :)  

#cfg_save
*** Storing configuration files from /etc/cfg/manifest -> ..
Shared object "libarchive.so.6" not found, required by "cpio"
dd: no value specified for of

**Comment by Cka3o4Huk** [comment]
12-CURRENT? What is SVN revision?

**Comment by dnybz** [comment]
FreeBSD 11.1.0 revision 328037

**Comment by dnybz** [comment]
Before using the FreeBSD 12.0-CURRENT # 11 r327331M version but there are bugs
# uname -a
FreeBSD freebsd-wifi 12.0-CURRENT FreeBSD 12.0-CURRENT #11 r327331M: Sun Jan 14 00:18:37 CST 2018     dnybz@dnybz:/data/freebsd/head/obj/mipsel_ap/data/freebsd/head/src/mips.mipsel/sys/MT7628_FDT  mips
# pid 214 (login), uid 0, was killed: out of swap space

Later, I replaced FreeBSD 11.1-RELEASE
FreeBSD freebsd-wifi 11.1-RELEASE FreeBSD 11.1-RELEASE #2 r328037M: Tue Jan 16 22:44:28 CST 2018     dnybz@dnybz:/data/freebsd/head/obj/mipsel_ap/mips.mipsel/data/freebsd/head/src/sys/MT7628_FDT  mips


Thx !  : )

**Comment by Cka3o4Huk** [comment]
AFAIK, freebsd-wifi supports only -CURRENT. releases & stables are badly supported.
I guess that you can try CURRENT again and fill bug here about "out of swap space". 

Probably I need to find one MT7628 board for CI testing. What is your board name? Is it like this: https://www.aliexpress.com/item/MTK-MT7628N-2x2-802-11-b-g-n-2-4GHz-2T2R-WLAN-Module-PCBA/32816761993.html?spm=2114.search0104.3.2.216aa881aKyqnz&ws_ab_test=searchweb0_0,searchweb201602_2_10152_10151_10065_10068_10344_10342_10343_10340_10341_10543_10084_10083_10307_10615_10301_10313_10059_10534_100031_10604_10103_10607_10606_10142,searchweb201603_25,ppcSwitch_4&algo_expid=706e561c-1d8e-4e28-99a7-5165b1f0e787-0&algo_pvid=706e561c-1d8e-4e28-99a7-5165b1f0e787&priceBeautifyAB=2?

**Comment by dnybz** [comment]
Hi
   My board is:
https://www.aliexpress.com/item/Openwrt-development-board-MT7628-module-serial-transmission-wifi-camera-super-MT7620a-7688/32813487868.html?spm=2114.search0104.3.118.2192cd42Z9Co3Q&ws_ab_test=searchweb0_0,searchweb201602_4_10152_10151_10065_10344_10068_10342_10325_10343_10546_10313_10059_10340_10548_10341_10534_100031_10084_10604_10083_10103_10307_10615_10142,searchweb201603_6,ppcSwitch_5&algo_expid=6f3093ad-c406-4350-85e2-709de51cbe48-18&algo_pvid=6f3093ad-c406-4350-85e2-709de51cbe48&priceBeautifyAB=4

**Comment by dnybz** [comment]
Hi 
   I tested FreeBSD 12 running on MT7268/265MB RAM/32MB SPI Flash is not fluent and almost inoperable. Thx ! :)

**Comment by dnybz** [comment]
Hi
   I found a solution, Thx! :) 
freebsd-wifi-build/bin/build_mfsroot
modify
${INSTALL_DEF_LIB} ${X_DESTDIR}/usr/lib/libarchive.so.7 ${X_STAGING_FSROOT}/usr/lib/
for
${INSTALL_DEF_LIB} ${X_DESTDIR}/usr/lib/libarchive.so.6 ${X_STAGING_FSROOT}/usr/lib/
