### ISSUE TITLE
Feature request: Enable build as a normal user instead of root

### ISSUE THREAD

**Issue by pastcompute** [freebsd/freebsd-wifi-build#20]
Even ignoring the security reasons for doing this, I managed to toast my build VM by accidentally copying mips binaries over the wrong place.

I solved this using my own script that calls `freebsd-wifi-build`, I uploaded it to https://github.com/pastcompute/carambola2-freebsd-userbuild 

I would be happy to try and port some of what it does back to `freebsd-wifi-build` but I dont know whether the required fixes would break anything for people that actually want to build as root for whatever reason.

The main things required:
* changing the variables passed to make.conf
* resolving issue #4 - I worked around it by chmodding /tftpboot & hacking a cp
* using fakeroot to do stuff
* Fixing #5 - I simply used `|| true` in my script to ignore the ko files

**Comment by erikarn** [comment]
Hi!

I've gone and merged in your stuff, but I then went in and redid it to use FreeBSD's user builds. Please sync and give it a go!

Thanks!


-adrian
