### ISSUE TITLE
Missing .ko files during build

### ISSUE THREAD

**Issue by katef** [freebsd/freebsd-wifi-build#5]
The build scripts (for carambola2, at least) attempt to install various .ko files - but these do not exist. That particular target then does "exit 1" - which seems appropriate to me, since the installation did indeed fail.

I suppose either the modules ought to be present, or if absent, ought not be installed.

**Comment by erikarn** [comment]
I've fixed this; now there's a modules list in the config file so you can explicitly state which modules to include.

**Comment by katef** [comment]
Thanks!
