### ISSUE TITLE
Missing lib80211.so.1 library

### ISSUE THREAD

**Issue by kprovost** [freebsd/freebsd-wifi-build#68]
With freebsd-wifi-build version d75f4303ebaefd3dd7922d8051ce148d97a0d6af and FreeBSD head I see the following multiple times during boot:

    Shared object "lib80211.so.1" not found, required by "ifconfig"

Presumably this is the result of the refactoring done in ifconfig.
Simply including the library in the build fixes the issue for me:

    diff --git a/build/bin/build_mfsroot b/build/bin/build_mfsroot
    index 2c1f0f4..733f1fb 100755
    --- a/build/bin/build_mfsroot
    +++ b/build/bin/build_mfsroot
    @@ -267,6 +267,7 @@ ${INSTALL_DEF_FILE} ${X_BASEDIR}/files/pf.conf ${X_STAGING_FSROOT}/c/etc/

     # networking
     ${INSTALL_DEF_BIN} ${X_DESTDIR}/sbin/ifconfig ${X_STAGING_FSROOT}/sbin/
    +${INSTALL_DEF_LIB} ${X_DESTDIR}/lib/lib80211.so.1 ${X_STAGING_FSROOT}/lib
     ${INSTALL_DEF_BIN} ${X_DESTDIR}/sbin/route ${X_STAGING_FSROOT}/sbin/
     ${INSTALL_DEF_BIN} ${X_DESTDIR}/sbin/ping ${X_STAGING_FSROOT}/sbin/
     ${INSTALL_DEF_BIN} ${X_DESTDIR}/sbin/ping6 ${X_STAGING_FSROOT}/sbin/

**Comment by erikarn** [comment]
should be fine now!

**Comment by kprovost** [comment]
Confirmed, this is fixed.
